data_config:
  #H_G: \image\distance \mask\distance_mask 480 x 496
  dataset_dir: D:\GLX\Projects\FQ2022\AttaNet\Dataset\2022.3.10

train_config:
  epochs: 100
  batch_size: 6
  output_dir: outputs

net_config:
  n_classes: 2
  learning_rate: 0.0001
