name: Eye_0325

data_config:
  #H_G: \image\distance \mask\distance_mask 480 x 496
  dataset_dir: E:\GLX\Datasets\Eye_0325

train_config:
  epochs: 100
  batch_size: 6
  output_dir: outputs

net_config:
  n_classes: 3
  learning_rate: 0.0001
